language: c
os: linux
dist: xenial
services:
  - docker
script:
  - bash tools/travis.sh
jobs:
  include:
    - env: OCAML_VERSION=4.08
    - env: OCAML_VERSION=4.09
  allow_failures:
    - env: OCAML_VERSION=4.09
