name: Create release from tag

on:
  push:
    tags:
      - '6.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install opam
      run: sudo apt-get install -y opam

    - name: Collect licenses
      run: ./tools/print-licenses.sh > licenses.txt

    - name: Archive upstream libraries
      run: make archive

    - name: Draft Release ${{ github.ref_name }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: true

    - name: Upload licenses.txt
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./licenses.txt
        asset_name: licenses.txt
        asset_content_type: text/plain

    - name: Upload xs-opam-repo-${{ github.ref_name }}.tar.gz
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./xs-opam-repo-${{ github.ref_name }}.tar.gz
        asset_name: xs-opam-repo-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip
