name: xs-toolstack build

on:
  push:
    branches:
      - master
      - 'release/*/lcm'
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: [4.08, 4.09]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the whole xs-toolstack
        run: bash tools/travis.sh
        env:
          OCAML_VERSION: ${{ matrix.ocaml-version }}
        continue-on-error: ${{ matrix.ocaml-version == 4.09 }}
