name: xs-toolstack build

on:
  push:
  pull_request:
  schedule:
    # run daily
    - cron: '41 3 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: ["4.08.1", "4.10.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the whole xs-toolstack
        run: bash tools/travis.sh
        env:
          OCAML_VERSION_FULL: ${{ matrix.ocaml-version }}
