name: Build and test

on:
  push:
  pull_request:
  schedule:
    # run daily
    - cron: '41 3 * * *'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: ["4.08.1", "4.10.1"]

    env:
      OCAML_VERSION: ${{ matrix.ocaml-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use ocaml
        uses: avsm/setup-ocaml@v1.1.2
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
          opam-repository: "."

      - name: Build xs-toolstack, test its dependencies
        run: |
          opam depext -vv -y xs-toolstack
          OPAMERRLOGLEN=10000 opam list -s --required-by xs-toolstack | xargs opam install -t
