name: xs-toolstack build

on:
  push:
    branches:
      - master
      - 'release/*/lcm'
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        env: [OPAMWITHTEST: false,
              OPAMWITHTEST: true,
              { OPAMWITHTEST: true,
                RECURSIVE: --recursive
              },
              { OPAMWITHTEST: true,
                OCAML_VERSION: 4.09
              }
             ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the whole xs-toolstack
        run: bash tools/travis.sh
        env: ${{ matrix.env }}
        continue-on-error: ${{ matrix.env.RECURSIVE == '--recursive' || matrix.env.OCAML_VERSION == 4.09 }}
