name: Build and test (Stockholm, scheduled)

on:
  schedule:
    # run daily
    - cron: '23 2 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'release/stockholm/lcm'
      - name: Build the whole xs-toolstack
        run: bash tools/travis.sh
        env:
          OCAML_VERSION: 4.08
          OPAMWITHTEST: true
